<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'currencies';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'code',
        'number',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'id',
    ];

    protected static array $currencies = [
        [
            'name' => 'Afghani',
            'code' => 'AFN',
            'number' => '971',
            'country' => 'AFGHANISTAN',
        ],
        [
            'name' => 'Lek',
            'code' => 'ALL',
            'number' => '008',
            'country' => 'ALBANIA',
        ],
        [
            'name' => 'Algerian Dinar',
            'code' => 'DZD',
            'number' => '012',
            'country' => 'ALGERIA',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'AMERICAN SAMOA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'ANDORRA',
        ],
        [
            'name' => 'Kwanza',
            'code' => 'AOA',
            'number' => '973',
            'country' => 'ANGOLA',
        ],
        [
            'name' => 'East Caribbean Dollar',
            'code' => 'XCD',
            'number' => '951',
            'country' => 'ANGUILLA',
        ],
        [
            'name' => 'No universal currency',
            'code' => null,
            'number' => null,
            'country' => 'ANTARCTICA',
        ],
        [
            'name' => 'East Caribbean Dollar',
            'code' => 'XCD',
            'number' => '951',
            'country' => 'ANTIGUA AND BARBUDA',
        ],
        [
            'name' => 'Argentine Peso',
            'code' => 'ARS',
            'number' => '032',
            'country' => 'ARGENTINA',
        ],
        [
            'name' => 'Armenian Dram',
            'code' => 'AMD',
            'number' => '051',
            'country' => 'ARMENIA',
        ],
        [
            'name' => 'Aruban Florin',
            'code' => 'AWG',
            'number' => '533',
            'country' => 'ARUBA',
        ],
        [
            'name' => 'Australian Dollar',
            'code' => 'AUD',
            'number' => '036',
            'country' => 'AUSTRALIA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'AUSTRIA',
        ],
        [
            'name' => 'Azerbaijanian Manat',
            'code' => 'AZN',
            'number' => '944',
            'country' => 'AZERBAIJAN',
        ],
        [
            'name' => 'Azerbaijanian Manat',
            'code' => 'AZN',
            'number' => '944',
            'country' => 'BAHAMAS (THE)',
        ],
        [
            'name' => 'Bahraini Dinar',
            'code' => 'BHD',
            'number' => '048',
            'country' => 'BAHRAIN',
        ],
        [
            'name' => 'Taka',
            'code' => 'BDT',
            'number' => '050',
            'country' => 'BANGLADESH',
        ],
        [
            'name' => 'Barbados Dollar',
            'code' => 'BBD',
            'number' => '052',
            'country' => 'BARBADOS',
        ],
        [
            'name' => 'Belarussian Ruble',
            'code' => 'BYN',
            'number' => '933',
            'country' => 'BELARUS',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'BELGIUM',
        ],
        [
            'name' => 'Belize Dollar',
            'code' => 'BZD',
            'number' => '084',
            'country' => 'BELIZE',
        ],
        [
            'name' => 'CFA Franc BCEAO',
            'code' => 'XOF',
            'number' => '952',
            'country' => 'BENIN',
        ],
        [
            'name' => 'CFA Franc BCEAO',
            'code' => 'XOF',
            'number' => '952',
            'country' => 'BENIN',
        ],
        [
            'name' => 'Bermudian Dollar',
            'code' => 'BMD',
            'number' => '060',
            'country' => 'BERMUDA',
        ],
        [
            'name' => 'Ngultrum',
            'code' => 'BTN',
            'number' => '064',
            'country' => 'BHUTAN',
        ],
        [
            'name' => 'Indian Rupee',
            'code' => 'INR',
            'number' => '356',
            'country' => 'BHUTAN',
        ],
        [
            'name' => 'Boliviano',
            'code' => 'BOB',
            'number' => '068',
            'country' => 'BOLIVIA (PLURINATIONAL STATE OF)',
        ],
        [
            'name' => 'Mvdol',
            'code' => 'BOV',
            'number' => '984',
            'country' => 'BOLIVIA (PLURINATIONAL STATE OF)',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'BONAIRE, SINT EUSTATIUS AND SABA',
        ],
        [
            'name' => 'Convertible Mark',
            'code' => 'BAM',
            'number' => '977',
            'country' => 'BOSNIA AND HERZEGOVINA',
        ],
        [
            'name' => 'Pula',
            'code' => 'BWP',
            'number' => '072',
            'country' => 'BOTSWANA',
        ],
        [
            'name' => 'Norwegian Krone',
            'code' => 'NOK',
            'number' => '578',
            'country' => 'BOUVET ISLAND',
        ],
        [
            'name' => 'Brazilian Real',
            'code' => 'BRL',
            'number' => '986',
            'country' => 'BRAZIL',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'BRITISH INDIAN OCEAN TERRITORY (THE)',
        ],
        [
            'name' => 'Brunei Dollar',
            'code' => 'BND',
            'number' => '096',
            'country' => 'BRUNEI DARUSSALAM',
        ],
        [
            'name' => 'Bulgarian Lev',
            'code' => 'BGN',
            'number' => '975',
            'country' => 'BULGARIA',
        ],
        [
            'name' => 'CFA Franc BCEAO',
            'code' => 'XOF',
            'number' => '952',
            'country' => 'BURKINA FASO',
        ],
        [
            'name' => 'Burundi Franc',
            'code' => 'BIF',
            'number' => '108',
            'country' => 'BURUNDI',
        ],
        [
            'name' => 'Cabo Verde Escudo',
            'code' => 'CVE',
            'number' => '132',
            'country' => 'CABO VERDE',
        ],
        [
            'name' => 'Riel',
            'code' => 'KHR',
            'number' => '116',
            'country' => 'CAMBODIA',
        ],
        [
            'name' => 'CFA Franc BEAC',
            'code' => 'XAF',
            'number' => '950',
            'country' => 'CAMEROON',
        ],
        [
            'name' => 'Canadian Dollar',
            'code' => 'CAD',
            'number' => '124',
            'country' => 'CANADA',
        ],
        [
            'name' => 'Cayman Islands Dollar',
            'code' => 'KYD',
            'number' => '136',
            'country' => 'CAYMAN ISLANDS (THE)',
        ],
        [
            'name' => 'CFA Franc BEAC',
            'code' => 'XAF',
            'number' => '950',
            'country' => 'CENTRAL AFRICAN REPUBLIC (THE)',
        ],
        [
            'name' => 'CFA Franc BEAC',
            'code' => 'XAF',
            'number' => '950',
            'country' => 'CHAD',
        ],
        [
            'name' => 'Unidad de Fomento',
            'code' => 'CLF',
            'number' => '990',
            'country' => 'CHILE',
        ],
        [
            'name' => 'Chilean Peso',
            'code' => 'CLP',
            'number' => '152',
            'country' => 'CHILE',
        ],
        [
            'name' => 'Yuan Renminbi',
            'code' => 'CNY',
            'number' => '156',
            'country' => 'CHINA',
        ],
        [
            'name' => 'Australian Dollar',
            'code' => 'AUD',
            'number' => '036',
            'country' => 'CHRISTMAS ISLAND',
        ],
        [
            'name' => 'Australian Dollar',
            'code' => 'AUD',
            'number' => '036',
            'country' => 'COCOS (KEELING) ISLANDS (THE)',
        ],
        [
            'name' => 'Colombian Peso',
            'code' => 'COP',
            'number' => '170',
            'country' => 'COLOMBIA',
        ],
        [
            'name' => 'Unidad de Valor Real',
            'code' => 'COU',
            'number' => '970',
            'country' => 'COLOMBIA',
        ],
        [
            'name' => 'Comoro Franc',
            'code' => 'KMF',
            'number' => '174',
            'country' => 'COMOROS (THE)',
        ],
        [
            'name' => 'Congolese Franc',
            'code' => 'CDF',
            'number' => '976',
            'country' => 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
        ],
        [
            'name' => 'CFA Franc BEAC',
            'code' => 'XAF',
            'number' => '950',
            'country' => 'CONGO (THE)',
        ],
        [
            'name' => 'New Zealand Dollar',
            'code' => 'NZD',
            'number' => '554',
            'country' => 'COOK ISLANDS (THE)',
        ],
        [
            'name' => 'Costa Rican Colon',
            'code' => 'CRC',
            'number' => '188',
            'country' => 'COSTA RICA',
        ],
        [
            'name' => 'Kuna',
            'code' => 'HRK',
            'number' => '191',
            'country' => 'CROATIA',
        ],
        [
            'name' => 'Peso Convertible',
            'code' => 'CUC',
            'number' => '931',
            'country' => 'CUBA',
        ],
        [
            'name' => 'Cuban Peso',
            'code' => 'CUP',
            'number' => '192',
            'country' => 'CUBA',
        ],
        [
            'name' => 'Netherlands Antillean Guilder',
            'code' => 'ANG',
            'number' => '532',
            'country' => 'CURAÇAO',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'CYPRUS',
        ],
        [
            'name' => 'Czech Koruna',
            'code' => 'CZK',
            'number' => '203',
            'country' => 'CZECH REPUBLIC (THE)',
        ],
        [
            'name' => 'CFA Franc BCEAO',
            'code' => 'XOF',
            'number' => '952',
            'country' => 'CÔTE D\'IVOIRE',
        ],
        [
            'name' => 'Danish Krone',
            'code' => 'DKK',
            'number' => '208',
            'country' => 'DENMARK',
        ],
        [
            'name' => 'Djibouti Franc',
            'code' => 'DJF',
            'number' => '262',
            'country' => 'DJIBOUTI',
        ],
        [
            'name' => 'East Caribbean Dollar',
            'code' => 'XCD',
            'number' => '951',
            'country' => 'DOMINICA',
        ],
        [
            'name' => 'Dominican Peso',
            'code' => 'DOP',
            'number' => '214',
            'country' => 'DOMINICAN REPUBLIC (THE)',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'ECUADOR',
        ],
        [
            'name' => 'Egyptian Pound',
            'code' => 'EGP',
            'number' => '818',
            'country' => 'EGYPT',
        ],
        [
            'name' => 'El Salvador Colon',
            'code' => 'SVC',
            'number' => '222',
            'country' => 'EL SALVADOR',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'EL SALVADOR',
        ],
        [
            'name' => 'CFA Franc BEAC',
            'code' => 'XAF',
            'number' => '950',
            'country' => 'EQUATORIAL GUINEA',
        ],
        [
            'name' => 'Nakfa',
            'code' => 'ERN',
            'number' => '232',
            'country' => 'ERITREA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'ESTONIA',
        ],
        [
            'name' => 'Ethiopian Birr',
            'code' => 'ETB',
            'number' => '230',
            'country' => 'ETHIOPIA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'EUROPEAN UNION',
        ],
        [
            'name' => 'Falkland Islands Pound',
            'code' => 'FKP',
            'number' => '238',
            'country' => 'FALKLAND ISLANDS (THE) [MALVINAS]',
        ],
        [
            'name' => 'Danish Krone',
            'code' => 'DKK',
            'number' => '208',
            'country' => 'FAROE ISLANDS (THE)',
        ],
        [
            'name' => 'Fiji Dollar',
            'code' => 'FJD',
            'number' => '242',
            'country' => 'FIJI',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'FINLAND',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'FRANCE',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'FRENCH GUIANA',
        ],
        [
            'name' => 'CFP Franc',
            'code' => 'XPF',
            'number' => '953',
            'country' => 'FRENCH POLYNESIA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'FRENCH SOUTHERN TERRITORIES (THE)',
        ],
        [
            'name' => 'CFA Franc BEAC',
            'code' => 'XAF',
            'number' => '950',
            'country' => 'GABON',
        ],
        [
            'name' => 'Dalasi',
            'code' => 'GMD',
            'number' => '270',
            'country' => 'GAMBIA (THE)',
        ],
        [
            'name' => 'Lari',
            'code' => 'GEL',
            'number' => '981',
            'country' => 'GEORGIA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'GERMANY',
        ],
        [
            'name' => 'Ghana Cedi',
            'code' => 'GHS',
            'number' => '936',
            'country' => 'GHANA',
        ],
        [
            'name' => 'Gibraltar Pound',
            'code' => 'GIP',
            'number' => '292',
            'country' => 'GIBRALTAR',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'GREECE',
        ],
        [
            'name' => 'Danish Krone',
            'code' => 'DKK',
            'number' => '208',
            'country' => 'GREENLAND',
        ],
        [
            'name' => 'East Caribbean Dollar',
            'code' => 'XCD',
            'number' => '951',
            'country' => 'GRENADA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'GUADELOUPE',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'GUAM',
        ],
        [
            'name' => 'Quetzal',
            'code' => 'GTQ',
            'number' => '320',
            'country' => 'GUATEMALA',
        ],
        [
            'name' => 'Pound Sterling',
            'code' => 'GBP',
            'number' => '826',
            'country' => 'GUERNSEY',
        ],
        [
            'name' => 'Guinea Franc',
            'code' => 'GNF',
            'number' => '324',
            'country' => 'GUINEA',
        ],
        [
            'name' => 'CFA Franc BCEAO',
            'code' => 'XOF',
            'number' => '952',
            'country' => 'GUINEA-BISSAU',
        ],
        [
            'name' => 'Guyana Dollar',
            'code' => 'GYD',
            'number' => '328',
            'country' => 'GUYANA',
        ],
        [
            'name' => 'Gourde',
            'code' => 'HTG',
            'number' => '332',
            'country' => 'HAITI',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'HAITI',
        ],
        [
            'name' => 'Australian Dollar',
            'code' => 'AUD',
            'number' => '036',
            'country' => 'HEARD ISLAND AND McDONALD ISLANDS',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'HOLY SEE (THE)',
        ],
        [
            'name' => 'Lempira',
            'code' => 'HNL',
            'number' => '340',
            'country' => 'HONDURAS',
        ],
        [
            'name' => 'Hong Kong Dollar',
            'code' => 'HKD',
            'number' => '344',
            'country' => 'HONG KONG',
        ],
        [
            'name' => 'Forint',
            'code' => 'HUF',
            'number' => '348',
            'country' => 'HUNGARY',
        ],
        [
            'name' => 'Iceland Krona',
            'code' => 'ISK',
            'number' => '352',
            'country' => 'ICELAND',
        ],
        [
            'name' => 'Indian Rupee',
            'code' => 'INR',
            'number' => '356',
            'country' => 'INDIA',
        ],
        [
            'name' => 'Rupiah',
            'code' => 'IDR',
            'number' => '360',
            'country' => 'INDONESIA',
        ],
        [
            'name' => 'SDR (Special Drawing Right)',
            'code' => 'XDR',
            'number' => '960',
            'country' => 'INTERNATIONAL MONETARY FUND (IMF)',
        ],
        [
            'name' => 'Iranian Rial',
            'code' => 'IRR',
            'number' => '364',
            'country' => 'IRAN (ISLAMIC REPUBLIC OF)',
        ],
        [
            'name' => 'Iraqi Dinar',
            'code' => 'IQD',
            'number' => '368',
            'country' => 'IRAQ',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'IRELAND',
        ],
        [
            'name' => 'Pound Sterling',
            'code' => 'GBP',
            'number' => '826',
            'country' => 'ISLE OF MAN',
        ],
        [
            'name' => 'New Israeli Sheqel',
            'code' => 'ILS',
            'number' => '376',
            'country' => 'ISRAEL',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'ITALY',
        ],
        [
            'name' => 'Jamaican Dollar',
            'code' => 'JMD',
            'number' => '388',
            'country' => 'JAMAICA',
        ],
        [
            'name' => 'Yen',
            'code' => 'JPY',
            'number' => '392',
            'country' => 'JAPAN',
        ],
        [
            'name' => 'Pound Sterling',
            'code' => 'GBP',
            'number' => '826',
            'country' => 'JERSEY',
        ],
        [
            'name' => 'Jordanian Dinar',
            'code' => 'JOD',
            'number' => '400',
            'country' => 'JORDAN',
        ],
        [
            'name' => 'Tenge',
            'code' => 'KZT',
            'number' => '398',
            'country' => 'KAZAKHSTAN',
        ],
        [
            'name' => 'Kenyan Shilling',
            'code' => 'KES',
            'number' => '404',
            'country' => 'KENYA',
        ],
        [
            'name' => 'Australian Dollar',
            'code' => 'AUD',
            'number' => '036',
            'country' => 'KIRIBATI',
        ],
        [
            'name' => 'North Korean Won',
            'code' => 'KPW',
            'number' => '408',
            'country' => 'KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)',
        ],
        [
            'name' => 'Won',
            'code' => 'KRW',
            'number' => '410',
            'country' => 'KOREA (THE REPUBLIC OF)',
        ],
        [
            'name' => 'Kuwaiti Dinar',
            'code' => 'KWD',
            'number' => '414',
            'country' => 'KUWAIT',
        ],
        [
            'name' => 'Som',
            'code' => 'KGS',
            'number' => '417',
            'country' => 'KYRGYZSTAN',
        ],
        [
            'name' => 'Kip',
            'code' => 'LAK',
            'number' => '418',
            'country' => 'LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'LATVIA',
        ],
        [
            'name' => 'Lebanese Pound',
            'code' => 'LBP',
            'number' => '422',
            'country' => 'LEBANON',
        ],
        [
            'name' => 'Loti',
            'code' => 'LSL',
            'number' => '426',
            'country' => 'LESOTHO',
        ],
        [
            'name' => 'Rand',
            'code' => 'ZAR',
            'number' => '710',
            'country' => 'LESOTHO',
        ],
        [
            'name' => 'Liberian Dollar',
            'code' => 'LRD',
            'number' => '430',
            'country' => 'LIBERIA',
        ],
        [
            'name' => 'Libyan Dinar',
            'code' => 'LYD',
            'number' => '434',
            'country' => 'LIBYA',
        ],
        [
            'name' => 'Swiss Franc',
            'code' => 'CHF',
            'number' => '756',
            'country' => 'LIECHTENSTEIN',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'LITHUANIA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'LUXEMBOURG',
        ],
        [
            'name' => 'Pataca',
            'code' => 'MOP',
            'number' => '446',
            'country' => 'MACAO',
        ],
        [
            'name' => 'Malagasy Ariary',
            'code' => 'MGA',
            'number' => '969',
            'country' => 'MADAGASCAR',
        ],
        [
            'name' => 'Kwacha',
            'code' => 'MWK',
            'number' => '454',
            'country' => 'MALAWI',
        ],
        [
            'name' => 'Malaysian Ringgit',
            'code' => 'MYR',
            'number' => '458',
            'country' => 'MALAYSIA',
        ],
        [
            'name' => 'Rufiyaa',
            'code' => 'MVR',
            'number' => '462',
            'country' => 'MALDIVES',
        ],
        [
            'name' => 'CFA Franc BCEAO',
            'code' => 'XOF',
            'number' => '952',
            'country' => 'MALI',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'MALTA',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'MARSHALL ISLANDS (THE)',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'MARTINIQUE',
        ],
        [
            'name' => 'Ouguiya',
            'code' => 'MRU',
            'number' => '929',
            'country' => 'MAURITANIA',
        ],
        [
            'name' => 'Mauritius Rupee',
            'code' => 'MUR',
            'number' => '480',
            'country' => 'MAURITIUS',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'MAYOTTE',
        ],
        [
            'name' => 'ADB Unit of Account',
            'code' => 'XUA',
            'number' => '965',
            'country' => 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP',
        ],
        [
            'name' => 'Mexican Peso',
            'code' => 'MXN',
            'number' => '484',
            'country' => 'MEXICO',
        ],
        [
            'name' => 'Mexican Unidad de Inversion (UDI)',
            'code' => 'MXV',
            'number' => '979',
            'country' => 'MEXICO',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'MICRONESIA (FEDERATED STATES OF)',
        ],
        [
            'name' => 'Moldovan Leu',
            'code' => 'MDL',
            'number' => '498',
            'country' => 'MOLDOVA (THE REPUBLIC OF)',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'MONACO',
        ],
        [
            'name' => 'Tugrik',
            'code' => 'MNT',
            'number' => '496',
            'country' => 'MONGOLIA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'MONTENEGRO',
        ],
        [
            'name' => 'East Caribbean Dollar',
            'code' => 'XCD',
            'number' => '951',
            'country' => 'MONTSERRAT',
        ],
        [
            'name' => 'Moroccan Dirham',
            'code' => 'MAD',
            'number' => '504',
            'country' => 'MOROCCO',
        ],
        [
            'name' => 'Mozambique Metical',
            'code' => 'MZN',
            'number' => '943',
            'country' => 'MOZAMBIQUE',
        ],
        [
            'name' => 'Kyat',
            'code' => 'MMK',
            'number' => '104',
            'country' => 'MYANMAR',
        ],
        [
            'name' => 'Namibia Dollar',
            'code' => 'NAD',
            'number' => '516',
            'country' => 'NAMIBIA',
        ],
        [
            'name' => 'Rand',
            'code' => 'ZAR',
            'number' => '710',
            'country' => 'NAMIBIA',
        ],
        [
            'name' => 'Australian Dollar',
            'code' => 'AUD',
            'number' => '036',
            'country' => 'NAURU',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'NETHERLANDS (THE)',
        ],
        [
            'name' => 'CFP Franc',
            'code' => 'XPF',
            'number' => '953',
            'country' => 'NEW CALEDONIA',
        ],
        [
            'name' => 'New Zealand Dollar',
            'code' => 'NZD',
            'number' => '554',
            'country' => 'NEW ZEALAND',
        ],
        [
            'name' => 'Cordoba Oro',
            'code' => 'NIO',
            'number' => '558',
            'country' => 'NICARAGUA',
        ],
        [
            'name' => 'CFA Franc BCEAO',
            'code' => 'XOF',
            'number' => '952',
            'country' => 'NIGER (THE)',
        ],
        [
            'name' => 'Naira',
            'code' => 'NGN',
            'number' => '566',
            'country' => 'NIGERIA',
        ],
        [
            'name' => 'New Zealand Dollar',
            'code' => 'NZD',
            'number' => '554',
            'country' => 'NIUE',
        ],
        [
            'name' => 'Australian Dollar',
            'code' => 'AUD',
            'number' => '036',
            'country' => 'NORFOLK ISLAND',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'NORTHERN MARIANA ISLANDS (THE)',
        ],
        [
            'name' => 'Norwegian Krone',
            'code' => 'NOK',
            'number' => '578',
            'country' => 'NORWAY',
        ],
        [
            'name' => 'Rial Omani',
            'code' => 'OMR',
            'number' => '512',
            'country' => 'OMAN',
        ],
        [
            'name' => 'Rial Omani',
            'code' => 'OMR',
            'number' => '512',
            'country' => 'OMAN',
        ],
        [
            'name' => 'Pakistan Rupee',
            'code' => 'PKR',
            'number' => '586',
            'country' => 'PAKISTAN',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'PALAU',
        ],
        [
            'name' => 'No universal currency',
            'code' => null,
            'number' => null,
            'country' => 'PALESTINE, STATE OF',
        ],
        [
            'name' => 'Balboa',
            'code' => 'PAB',
            'number' => '590',
            'country' => 'PANAMA',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'PANAMA',
        ],
        [
            'name' => 'Kina',
            'code' => 'PGK',
            'number' => '598',
            'country' => 'PAPUA NEW GUINEA',
        ],
        [
            'name' => 'Guarani',
            'code' => 'PYG',
            'number' => '600',
            'country' => 'PARAGUAY',
        ],
        [
            'name' => 'Nuevo Sol',
            'code' => 'PEN',
            'number' => '604',
            'country' => 'PERU',
        ],
        [
            'name' => 'Philippine Peso',
            'code' => 'PHP',
            'number' => '608',
            'country' => 'PHILIPPINES (THE)',
        ],
        [
            'name' => 'New Zealand Dollar',
            'code' => 'NZD',
            'number' => '554',
            'country' => 'PITCAIRN',
        ],
        [
            'name' => 'Zloty',
            'code' => 'PLN',
            'number' => '985',
            'country' => 'POLAND',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'PORTUGAL',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'PUERTO RICO',
        ],
        [
            'name' => 'Qatari Rial',
            'code' => 'QAR',
            'number' => '634',
            'country' => 'QATAR',
        ],
        [
            'name' => 'Denar',
            'code' => 'MKD',
            'number' => '807',
            'country' => 'REPUBLIC OF NORTH MACEDONIA',
        ],
        [
            'name' => 'Romanian Leu',
            'code' => 'RON',
            'number' => '946',
            'country' => 'ROMANIA',
        ],
        [
            'name' => 'Russian Ruble',
            'code' => 'RUB',
            'number' => '643',
            'country' => 'RUSSIAN FEDERATION (THE)',
        ],
        [
            'name' => 'Rwanda Franc',
            'code' => 'RWF',
            'number' => '646',
            'country' => 'RWANDA',
        ],
        [
            'name' => 'Rwanda Franc',
            'code' => 'RWF',
            'number' => '646',
            'country' => 'RWANDA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'RÉUNION',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'SAINT BARTHÉLEMY',
        ],
        [
            'name' => 'Saint Helena Pound',
            'code' => 'SHP',
            'number' => '654',
            'country' => 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
        ],
        [
            'name' => 'East Caribbean Dollar',
            'code' => 'XCD',
            'number' => '951',
            'country' => 'SAINT KITTS AND NEVIS',
        ],
        [
            'name' => 'East Caribbean Dollar',
            'code' => 'XCD',
            'number' => '951',
            'country' => 'SAINT LUCIA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'SAINT MARTIN (FRENCH PART)',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'SAINT PIERRE AND MIQUELON',
        ],
        [
            'name' => 'East Caribbean Dollar',
            'code' => 'XCD',
            'number' => '951',
            'country' => 'SAINT VINCENT AND THE GRENADINES',
        ],
        [
            'name' => 'Tala',
            'code' => 'WST',
            'number' => '882',
            'country' => 'SAMOA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'SAN MARINO',
        ],
        [
            'name' => 'Dobra',
            'code' => 'STN',
            'number' => '930',
            'country' => 'SAO TOME AND PRINCIPE',
        ],
        [
            'name' => 'Saudi Riyal',
            'code' => 'SAR',
            'number' => '682',
            'country' => 'SAUDI ARABIA',
        ],
        [
            'name' => 'CFA Franc BCEAO',
            'code' => 'XOF',
            'number' => '952',
            'country' => 'SENEGAL',
        ],
        [
            'name' => 'Serbian Dinar',
            'code' => 'RSD',
            'number' => '941',
            'country' => 'SERBIA',
        ],
        [
            'name' => 'Seychelles Rupee',
            'code' => 'SCR',
            'number' => '690',
            'country' => 'SEYCHELLES',
        ],
        [
            'name' => 'Leone',
            'code' => 'SLL',
            'number' => '694',
            'country' => 'SIERRA LEONE',
        ],
        [
            'name' => 'Singapore Dollar',
            'code' => 'SGD',
            'number' => '702',
            'country' => 'SINGAPORE',
        ],
        [
            'name' => 'Netherlands Antillean Guilder',
            'code' => 'ANG',
            'number' => '532',
            'country' => 'SINT MAARTEN (DUTCH PART)',
        ],
        [
            'name' => 'Sucre',
            'code' => 'XSU',
            'number' => '994',
            'country' => 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'SLOVAKIA',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'SLOVENIA',
        ],
        [
            'name' => 'Solomon Islands Dollar',
            'code' => 'SBD',
            'number' => '090',
            'country' => 'SOLOMON ISLANDS',
        ],
        [
            'name' => 'Somali Shilling',
            'code' => 'SOS',
            'number' => '706',
            'country' => 'SOMALIA',
        ],
        [
            'name' => 'Rand',
            'code' => 'ZAR',
            'number' => '710',
            'country' => 'SOUTH AFRICA',
        ],
        [
            'name' => 'No universal currency',
            'code' => null,
            'number' => null,
            'country' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
        ],
        [
            'name' => 'South Sudanese Pound',
            'code' => 'SSP',
            'number' => '728',
            'country' => 'SOUTH SUDAN',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'SPAIN',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'SPAIN',
        ],
        [
            'name' => 'Sri Lanka Rupee',
            'code' => 'LKR',
            'number' => '144',
            'country' => 'SRI LANKA',
        ],
        [
            'name' => 'Sudanese Pound',
            'code' => 'SDG',
            'number' => '938',
            'country' => 'SUDAN (THE)',
        ],
        [
            'name' => 'Surinam Dollar',
            'code' => 'SRD',
            'number' => '968',
            'country' => 'SURINAME',
        ],
        [
            'name' => 'Norwegian Krone',
            'code' => 'NOK',
            'number' => '578',
            'country' => 'SVALBARD AND JAN MAYEN',
        ],
        [
            'name' => 'Lilangeni',
            'code' => 'SZL',
            'number' => '748',
            'country' => 'SWAZILAND',
        ],
        [
            'name' => 'Swedish Krona',
            'code' => 'SEK',
            'number' => '752',
            'country' => 'SWEDEN',
        ],
        [
            'name' => 'WIR Euro',
            'code' => 'CHE',
            'number' => '947',
            'country' => 'SWITZERLAND',
        ],
        [
            'name' => 'Swiss Franc',
            'code' => 'CHF',
            'number' => '756',
            'country' => 'SWITZERLAND',
        ],
        [
            'name' => 'WIR Franc',
            'code' => 'CHW',
            'number' => '948',
            'country' => 'SWITZERLAND',
        ],
        [
            'name' => 'Syrian Pound',
            'code' => 'SYP',
            'number' => '760',
            'country' => 'SYRIAN ARAB REPUBLIC',
        ],
        [
            'name' => 'New Taiwan Dollar',
            'code' => 'TWD',
            'number' => '901',
            'country' => 'TAIWAN (PROVINCE OF CHINA)',
        ],
        [
            'name' => 'Somoni',
            'code' => 'TJS',
            'number' => '972',
            'country' => 'TAJIKISTAN',
        ],
        [
            'name' => 'Tanzanian Shilling',
            'code' => 'TZS',
            'number' => '834',
            'country' => 'TANZANIA, UNITED REPUBLIC OF',
        ],
        [
            'name' => 'Baht',
            'code' => 'THB',
            'number' => '764',
            'country' => 'THAILAND',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'TIMOR-LESTE',
        ],
        [
            'name' => 'CFA Franc BCEAO',
            'code' => 'XOF',
            'number' => '952',
            'country' => 'TOGO',
        ],
        [
            'name' => 'New Zealand Dollar',
            'code' => 'NZD',
            'number' => '554',
            'country' => 'TOKELAU',
        ],
        [
            'name' => 'Pa’anga',
            'code' => 'TOP',
            'number' => '776',
            'country' => 'TONGA',
        ],
        [
            'name' => 'Trinidad and Tobago Dollar',
            'code' => 'TTD',
            'number' => '780',
            'country' => 'TRINIDAD AND TOBAGO',
        ],
        [
            'name' => 'Tunisian Dinar',
            'code' => 'TND',
            'number' => '788',
            'country' => 'TUNISIA',
        ],
        [
            'name' => 'Turkish Lira',
            'code' => 'TRY',
            'number' => '949',
            'country' => 'TURKEY',
        ],
        [
            'name' => 'Turkmenistan New Manat',
            'code' => 'TMT',
            'number' => '934',
            'country' => 'TURKMENISTAN',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'TURKS AND CAICOS ISLANDS (THE)',
        ],
        [
            'name' => 'Australian Dollar',
            'code' => 'AUD',
            'number' => '036',
            'country' => 'TUVALU',
        ],
        [
            'name' => 'Uganda Shilling',
            'code' => 'UGX',
            'number' => '800',
            'country' => 'UGANDA',
        ],
        [
            'name' => 'Hryvnia',
            'code' => 'UAH',
            'number' => '980',
            'country' => 'UKRAINE',
        ],
        [
            'name' => 'UAE Dirham',
            'code' => 'AED',
            'number' => '784',
            'country' => 'UNITED ARAB EMIRATES (THE)',
        ],
        [
            'name' => 'Pound Sterling',
            'code' => 'GBP',
            'number' => '826',
            'country' => 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'UNITED STATES OF AMERICA (THE)',
        ],
        [
            'name' => 'US Dollar (Next day)',
            'code' => 'USN',
            'number' => '997',
            'country' => 'UNITED STATES OF AMERICA (THE)',
        ],
        [
            'name' => 'Uruguay Peso en Unidades Indexadas (URUIURUI)',
            'code' => 'UYI',
            'number' => '940',
            'country' => 'URUGUAY',
        ],
        [
            'name' => 'Peso Uruguayo',
            'code' => 'UYU',
            'number' => '858',
            'country' => 'URUGUAY',
        ],
        [
            'name' => 'Uzbekistan Sum',
            'code' => 'UZS',
            'number' => '860',
            'country' => 'UZBEKISTAN',
        ],
        [
            'name' => 'Vatu',
            'code' => 'VUV',
            'number' => '548',
            'country' => 'VANUATU',
        ],
        [
            'name' => 'Bolivar',
            'code' => 'VEF',
            'number' => '937',
            'country' => 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
        ],
        [
            'name' => 'Dong',
            'code' => 'VND',
            'number' => '704',
            'country' => 'VIET NAM',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'VIRGIN ISLANDS (BRITISH)',
        ],
        [
            'name' => 'US Dollar',
            'code' => 'USD',
            'number' => '840',
            'country' => 'VIRGIN ISLANDS (U.S.)',
        ],
        [
            'name' => 'CFP Franc',
            'code' => 'XPF',
            'number' => '953',
            'country' => 'WALLIS AND FUTUNA',
        ],
        [
            'name' => 'Moroccan Dirham',
            'code' => 'MAD',
            'number' => '504',
            'country' => 'WESTERN SAHARA',
        ],
        [
            'name' => 'Yemeni Rial',
            'code' => 'YER',
            'number' => '886',
            'country' => 'YEMEN',
        ],
        [
            'name' => 'Zambian Kwacha',
            'code' => 'ZMW',
            'number' => '967',
            'country' => 'ZAMBIA',
        ],
        [
            'name' => 'Zimbabwe Dollar',
            'code' => 'ZWL',
            'number' => '932',
            'country' => 'ZIMBABWE',
        ],
        [
            'name' => 'Euro',
            'code' => 'EUR',
            'number' => '978',
            'country' => 'ÅLAND ISLANDS',
        ],
    ];

    public static function getCurrencies(): array
    {
        return static::$currencies;
    }
}
